/* ============================================================================
 * include/engine/recovered_structs.h - Type-B composed candidates (Phase 4B)
 * machine-generated by tools/recover_structs.py - DRAFT review surface.
 * Trailing fields compete with an unshared, larger context: the group only
 * proves that these offsets co-occur inside one object layout, not that the
 * struct starts at the first offset. Names are layout-derived; do not use
 * in signatures.h until a human promotes them.
 * ======================================================================== */

#ifndef _CNK_ENGINE_RECOVERED_STRUCTS_H
#define _CNK_ENGINE_RECOVERED_STRUCTS_H

/* 14 candidates (strength >= 3 co-occurring functions) */

/* ------------------------------------------------------------
 * Unknown_a0_0x18c_0x190_0x198_0x19c_0x1a0_0x1a4_0x1a8_0x1ac_0x1b0_0x1b8_0x1bc_0x1c4_0x1c8_0x1cc_0x1d8_0x1dc_0x218_0x234_0x238_0x23c_0x240_0x248_0x24c_0x254_0x258_0x25c_0x260_0x264_0x268_0x26c_0x270_0x274_0x278_0x27c_0x280_0x284_0x288_0x294_0x298_0x29c_0x2a0_0x2a4_0x2a8_0x2ac_0x2b0_0x2b4_0x2b8_0x2bc_0x2c0_0x2c4_0x2cc_0x2d4_0x2d8_0x2dc_0x42c  arg a0  strength 3
 * comment: PROMOTE ME -> rename and rewrite members
 * offsets: 0x18c, 0x190, 0x198, 0x19c, 0x1a0, 0x1a4, 0x1a8, 0x1ac, 0x1b0, 0x1b8, 0x1bc, 0x1c4, 0x1c8, 0x1cc, 0x1d8, 0x1dc, 0x218, 0x234, 0x238, 0x23c, 0x240, 0x248, 0x24c, 0x254, 0x258, 0x25c, 0x260, 0x264, 0x268, 0x26c, 0x270, 0x274, 0x278, 0x27c, 0x280, 0x284, 0x288, 0x294, 0x298, 0x29c, 0x2a0, 0x2a4, 0x2a8, 0x2ac, 0x2b0, 0x2b4, 0x2b8, 0x2bc, 0x2c0, 0x2c4, 0x2cc, 0x2d4, 0x2d8, 0x2dc, 0x42c
 * ------------------------------------------------------------ */
// struct Unknown_a0_0x18c_0x190_0x198_0x19c_0x1a0_0x1a4_0x1a8_0x1ac_0x1b0_0x1b8_0x1bc_0x1c4_0x1c8_0x1cc_0x1d8_0x1dc_0x218_0x234_0x238_0x23c_0x240_0x248_0x24c_0x254_0x258_0x25c_0x260_0x264_0x268_0x26c_0x270_0x274_0x278_0x27c_0x280_0x284_0x288_0x294_0x298_0x29c_0x2a0_0x2a4_0x2a8_0x2ac_0x2b0_0x2b4_0x2b8_0x2bc_0x2c0_0x2c4_0x2cc_0x2d4_0x2d8_0x2dc_0x42c {
//     f32 f_0x18c; /* ev 7 */
//     f32 f_0x190; /* ev 10 */
//     f32 f_0x198; /* ev 9 */
//     u32 f_0x19c; /* ev 6 */
//     u32 f_0x1a0; /* ev 10 */
//     f32 f_0x1a4; /* ev 8 */
//     u32 f_0x1a8; /* ev 6 */
//     u32 f_0x1ac; /* ev 5 */
//     f32 f_0x1b0; /* ev 21 */
//     u32 f_0x1b8; /* ev 8 */
//     u32 f_0x1bc; /* ev 6 */
//     u32 f_0x1c4; /* ev 5 */
//     u32 f_0x1c8; /* ev 6 */
//     u32 f_0x1cc; /* ev 4 */
//     u32 f_0x1d8; /* ev 6 */
//     u32 f_0x1dc; /* ev 5 */
//     f32 f_0x218; /* ev 3 */
//     u32 f_0x234; /* ev 6 */
//     u32 f_0x238; /* ev 4 */
//     u32 f_0x23c; /* ev 4 */
//     u32 f_0x240; /* ev 5 */
//     u32 f_0x248; /* ev 4 */
//     u32 f_0x24c; /* ev 6 */
//     u32 f_0x254; /* ev 3 */
//     u32 f_0x258; /* ev 4 */
//     u32 f_0x25c; /* ev 4 */
//     u32 f_0x260; /* ev 3 */
//     u32 f_0x264; /* ev 4 */
//     f32 f_0x268; /* ev 4 */
//     u32 f_0x26c; /* ev 3 */
//     u32 f_0x270; /* ev 3 */
//     u32 f_0x274; /* ev 5 */
//     u32 f_0x278; /* ev 3 */
//     u32 f_0x27c; /* ev 3 */
//     u32 f_0x280; /* ev 3 */
//     u32 f_0x284; /* ev 3 */
//     u32 f_0x288; /* ev 3 */
//     u32 f_0x294; /* ev 13 */
//     u32 f_0x298; /* ev 3 */
//     u32 f_0x29c; /* ev 3 */
//     u32 f_0x2a0; /* ev 4 */
//     u32 f_0x2a4; /* ev 5 */
//     u32 f_0x2a8; /* ev 3 */
//     u32 f_0x2ac; /* ev 8 */
//     u32 f_0x2b0; /* ev 5 */
//     u32 f_0x2b4; /* ev 5 */
//     u32 f_0x2b8; /* ev 4 */
//     u32 f_0x2bc; /* ev 4 */
//     /* ... 7 more members ... */
// };

/* ------------------------------------------------------------
 * Unknown_a0_0x31_0x32_0x33_0x35_0x41_0x42_0x59_0x5a_0x5b_0x5d_0x5e_0x5f_0x61_0x62_0x89_0x99_0x9b_0xb1_0xb2_0xb3_0xf5_0x111_0x165  arg a0  strength 3
 * comment: PROMOTE ME -> rename and rewrite members
 * offsets: 0x31, 0x32, 0x33, 0x35, 0x41, 0x42, 0x59, 0x5a, 0x5b, 0x5d, 0x5e, 0x5f, 0x61, 0x62, 0x89, 0x99, 0x9b, 0xb1, 0xb2, 0xb3, 0xf5, 0x111, 0x165
 * ------------------------------------------------------------ */
// struct Unknown_a0_0x31_0x32_0x33_0x35_0x41_0x42_0x59_0x5a_0x5b_0x5d_0x5e_0x5f_0x61_0x62_0x89_0x99_0x9b_0xb1_0xb2_0xb3_0xf5_0x111_0x165 {
//     u8 f_0x31; /* ev 5 */
//     u8 f_0x32; /* ev 4 */
//     u8 f_0x33; /* ev 4 */
//     u8 f_0x35; /* ev 10 */
//     u8 f_0x41; /* ev 6 */
//     u8 f_0x42; /* ev 7 */
//     u8 f_0x59; /* ev 3 */
//     u8 f_0x5a; /* ev 3 */
//     u8 f_0x5b; /* ev 3 */
//     u8 f_0x5d; /* ev 3 */
//     u8 f_0x5e; /* ev 3 */
//     u8 f_0x5f; /* ev 3 */
//     u8 f_0x61; /* ev 3 */
//     u8 f_0x62; /* ev 3 */
//     u8 f_0x89; /* ev 3 */
//     u8 f_0x99; /* ev 3 */
//     u8 f_0x9b; /* ev 3 */
//     u8 f_0xb1; /* ev 7 */
//     u8 f_0xb2; /* ev 3 */
//     u8 f_0xb3; /* ev 3 */
//     u8 f_0xf5; /* ev 3 */
//     u8 f_0x111; /* ev 4 */
//     u8 f_0x165; /* ev 3 */
// };

/* ------------------------------------------------------------
 * Unknown_a1_0x6_0x7_0xb_0xe_0xf_0x13_0x17_0x19_0x1a_0x1b_0x1d_0x1f  arg a1  strength 3
 * comment: PROMOTE ME -> rename and rewrite members
 * offsets: 0x6, 0x7, 0xb, 0xe, 0xf, 0x13, 0x17, 0x19, 0x1a, 0x1b, 0x1d, 0x1f
 * ------------------------------------------------------------ */
// struct Unknown_a1_0x6_0x7_0xb_0xe_0xf_0x13_0x17_0x19_0x1a_0x1b_0x1d_0x1f {
//     u8 f_0x6; /* ev 5 */
//     u8 f_0x7; /* ev 5 */
//     u8 f_0xb; /* ev 6 */
//     u8 f_0xe; /* ev 3 */
//     u8 f_0xf; /* ev 6 */
//     u8 f_0x13; /* ev 3 */
//     u8 f_0x17; /* ev 5 */
//     u8 f_0x19; /* ev 4 */
//     u8 f_0x1a; /* ev 5 */
//     u8 f_0x1b; /* ev 4 */
//     u8 f_0x1d; /* ev 6 */
//     u8 f_0x1f; /* ev 3 */
// };

/* ------------------------------------------------------------
 * Unknown_a0_0x4a8_0x4ac_0x4b0_0x4b4_0x4b8_0x4bc_0x4c0_0x4dc_0x4e0_0x4e4  arg a0  strength 3
 * comment: PROMOTE ME -> rename and rewrite members
 * offsets: 0x4a8, 0x4ac, 0x4b0, 0x4b4, 0x4b8, 0x4bc, 0x4c0, 0x4dc, 0x4e0, 0x4e4
 * ------------------------------------------------------------ */
// struct Unknown_a0_0x4a8_0x4ac_0x4b0_0x4b4_0x4b8_0x4bc_0x4c0_0x4dc_0x4e0_0x4e4 {
//     u32 f_0x4a8; /* ev 3 */
//     u32 f_0x4ac; /* ev 3 */
//     u32 f_0x4b0; /* ev 3 */
//     u32 f_0x4b4; /* ev 3 */
//     u32 f_0x4b8; /* ev 3 */
//     u32 f_0x4bc; /* ev 3 */
//     f32 f_0x4c0; /* ev 3 */
//     u32 f_0x4dc; /* ev 3 */
//     u32 f_0x4e0; /* ev 4 */
//     u32 f_0x4e4; /* ev 4 */
// };

/* ------------------------------------------------------------
 * Unknown_a0_0x3c4_0x3c8_0x3cc_0x3d4_0x3d8_0x3dc_0x3e0  arg a0  strength 3
 * comment: PROMOTE ME -> rename and rewrite members
 * offsets: 0x3c4, 0x3c8, 0x3cc, 0x3d4, 0x3d8, 0x3dc, 0x3e0
 * ------------------------------------------------------------ */
// struct Unknown_a0_0x3c4_0x3c8_0x3cc_0x3d4_0x3d8_0x3dc_0x3e0 {
//     u32 f_0x3c4; /* ev 3 */
//     u32 f_0x3c8; /* ev 3 */
//     u32 f_0x3cc; /* ev 3 */
//     u32 f_0x3d4; /* ev 4 */
//     u32 f_0x3d8; /* ev 4 */
//     u32 f_0x3dc; /* ev 4 */
//     u32 f_0x3e0; /* ev 13 */
// };

/* ------------------------------------------------------------
 * Unknown_a0_0x38c_0x390_0x394_0x398  arg a0  strength 3
 * comment: PROMOTE ME -> rename and rewrite members
 * offsets: 0x38c, 0x390, 0x394, 0x398
 * ------------------------------------------------------------ */
// struct Unknown_a0_0x38c_0x390_0x394_0x398 {
//     u32 f_0x38c; /* ev 3 */
//     f32 f_0x390; /* ev 6 */
//     u32 f_0x394; /* ev 3 */
//     u32 f_0x398; /* ev 3 */
// };

/* ------------------------------------------------------------
 * Unknown_a0_0x4c8_0x4cc_0x4d0_0x4d4  arg a0  strength 3
 * comment: PROMOTE ME -> rename and rewrite members
 * offsets: 0x4c8, 0x4cc, 0x4d0, 0x4d4
 * ------------------------------------------------------------ */
// struct Unknown_a0_0x4c8_0x4cc_0x4d0_0x4d4 {
//     u32 f_0x4c8; /* ev 3 */
//     u32 f_0x4cc; /* ev 4 */
//     u32 f_0x4d0; /* ev 4 */
//     u32 f_0x4d4; /* ev 6 */
// };

/* ------------------------------------------------------------
 * Unknown_a2_0x-2ca2_0x-2c9e_0x-2c92_0x-288f  arg a2  strength 3
 * comment: PROMOTE ME -> rename and rewrite members
 * offsets: 0x-2ca2, 0x-2c9e, 0x-2c92, 0x-288f
 * ------------------------------------------------------------ */
// struct Unknown_a2_0x-2ca2_0x-2c9e_0x-2c92_0x-288f {
//     u32 f_0x-2ca2; /* ev 4 */
//     u32 f_0x-2c9e; /* ev 4 */
//     u32 f_0x-2c92; /* ev 3 */
//     u8 f_0x-288f; /* ev 4 */
// };

/* ------------------------------------------------------------
 * Unknown_a3_0x-7c_0x-78_0x-74_0x-10  arg a3  strength 3
 * comment: PROMOTE ME -> rename and rewrite members
 * offsets: 0x-7c, 0x-78, 0x-74, 0x-10
 * ------------------------------------------------------------ */
// struct Unknown_a3_0x-7c_0x-78_0x-74_0x-10 {
//     u32 f_0x-7c; /* ev 3 */
//     u32 f_0x-78; /* ev 3 */
//     u32 f_0x-74; /* ev 3 */
//     u32 f_0x-10; /* ev 3 */
// };

/* ------------------------------------------------------------
 * Unknown_a2_0x1c_0x34_0x3c  arg a2  strength 3
 * comment: PROMOTE ME -> rename and rewrite members
 * offsets: 0x1c, 0x34, 0x3c
 * ------------------------------------------------------------ */
// struct Unknown_a2_0x1c_0x34_0x3c {
//     u32 f_0x1c; /* ev 11 */
//     u32 f_0x34; /* ev 14 */
//     u32 f_0x3c; /* ev 3 */
// };

/* ------------------------------------------------------------
 * Unknown_a0_0x3_0x7dc  arg a0  strength 4
 * comment: PROMOTE ME -> rename and rewrite members
 * offsets: 0x3, 0x7dc
 * ------------------------------------------------------------ */
// struct Unknown_a0_0x3_0x7dc {
//     u8 f_0x3; /* ev 14 */
//     u32 f_0x7dc; /* ev 4 */
// };

/* ------------------------------------------------------------
 * Unknown_a0_0x28c_0x290  arg a0  strength 4
 * comment: PROMOTE ME -> rename and rewrite members
 * offsets: 0x28c, 0x290
 * ------------------------------------------------------------ */
// struct Unknown_a0_0x28c_0x290 {
//     u32 f_0x28c; /* ev 4 */
//     void * f_0x290; /* ev 5 */
// };

/* ------------------------------------------------------------
 * Unknown_a0_0x340_0x344  arg a0  strength 3
 * comment: PROMOTE ME -> rename and rewrite members
 * offsets: 0x340, 0x344
 * ------------------------------------------------------------ */
// struct Unknown_a0_0x340_0x344 {
//     u32 f_0x340; /* ev 3 */
//     u32 f_0x344; /* ev 3 */
// };

/* ------------------------------------------------------------
 * Unknown_a0_0x4e8_0x508  arg a0  strength 3
 * comment: PROMOTE ME -> rename and rewrite members
 * offsets: 0x4e8, 0x508
 * ------------------------------------------------------------ */
// struct Unknown_a0_0x4e8_0x508 {
//     u32 f_0x4e8; /* ev 5 */
//     u32 f_0x508; /* ev 3 */
// };

#endif
