/* ============================================================================
 * include/engine/types.h - Phase 3E promoted anonymous structs (SLUS_206.49)
 * machine-generated by tools/emit_structs.py; regenerate, do not hand-edit.
 * Layout-derived names are deterministic from (arg, offsets): no invented ids.
 * Promotion: evidence >= 10, members >= 3, fields >= 2 (of 506 candidates).
 * ======================================================================== */

#ifndef _CNK_ENGINE_TYPES_H
#define _CNK_ENGINE_TYPES_H

typedef unsigned char   u8;
typedef unsigned short  u16;
typedef unsigned int    u32;
typedef unsigned long long u64;
typedef float           f32;

/* --- 34 struct bodies --- */

/* Unknown_a0_4_8  fields=2  evidence=382  members=40  role=float-pack
 */
struct Unknown_a0_4_8 {
    u8 _pad_0x0[0x4];
    f32 f_0x4;   /* also deref'd */
    f32 f_0x8;   /* also deref'd */
};

/* Unknown_a0_0_1c  fields=2  evidence=105  members=40  role=object-like
 */
struct Unknown_a0_0_1c {
    void * f_0x0;
    u8 _pad_0x4[0x18];
    u32 f_0x1c;
};

/* Unknown_a0_0_4  fields=2  evidence=94  members=40  role=vec2f
 */
struct Unknown_a0_0_4 {
    f32 f_0x0;   /* also deref'd */
    f32 f_0x4;   /* also deref'd */
};

/* Unknown_a1_0_4  fields=2  evidence=83  members=40  role=vec2f
 */
struct Unknown_a1_0_4 {
    f32 f_0x0;   /* also deref'd */
    f32 f_0x4;   /* also deref'd */
};

/* Unknown_a0_8_c  fields=2  evidence=77  members=40  role=float-pack
 */
struct Unknown_a0_8_c {
    u8 _pad_0x0[0x8];
    f32 f_0x8;   /* also deref'd */
    f32 f_0xc;   /* also deref'd */
};

/* Unknown_a0_0_4_8_c  fields=4  evidence=66  members=40  role=vec4f
 *   real members: 38d0(FUN_001238d0), ba30(FUN_0015ba30), cde0(FUN_001acde0), 82f0(FUN_001b82f0), 3470(FUN_001c3470), a130(FUN_001ca130)
 */
struct Unknown_a0_0_4_8_c {
    f32 f_0x0;   /* also deref'd */
    f32 f_0x4;
    f32 f_0x8;   /* also deref'd */
    f32 f_0xc;   /* also deref'd */
};

/* Unknown_a1_0_4_8  fields=3  evidence=43  members=40  role=vec3f
 *   real members: ba30(FUN_0015ba30), cde0(FUN_001acde0), 82f0(FUN_001b82f0), 3470(FUN_001c3470), ad90(FUN_001cad90), f680(FUN_001cf680)
 */
struct Unknown_a1_0_4_8 {
    f32 f_0x0;   /* also deref'd */
    f32 f_0x4;
    f32 f_0x8;   /* also deref'd */
};

/* Unknown_a0_0_4c  fields=2  evidence=35  members=35  role=object-like
 */
struct Unknown_a0_0_4c {
    void * f_0x0;
    u8 _pad_0x4[0x48];
    u32 f_0x4c;
};

/* Unknown_a0_0_8  fields=2  evidence=35  members=35  role=object-like
 */
struct Unknown_a0_0_8 {
    void * f_0x0;
    u8 _pad_0x4[0x4];
    void * f_0x8;
};

/* Unknown_a0_0_20  fields=2  evidence=28  members=28  role=object-like
 */
struct Unknown_a0_0_20 {
    void * f_0x0;
    u8 _pad_0x4[0x1c];
    void * f_0x20;
};

/* Unknown_a0_0_4_8  fields=3  evidence=26  members=26  role=vec3f
 *   real members: e950(FUN_0013e950), d1a0(FUN_0022d1a0), 04a0(FUN_002304a0)
 */
struct Unknown_a0_0_4_8 {
    f32 f_0x0;   /* also deref'd */
    f32 f_0x4;   /* also deref'd */
    f32 f_0x8;   /* also deref'd */
};

/* Unknown_a1_0_10  fields=2  evidence=25  members=25  role=float-pack
 */
struct Unknown_a1_0_10 {
    f32 f_0x0;
    u8 _pad_0x4[0xc];
    f32 f_0x10[4];
};

/* Unknown_a1_c_10  fields=2  evidence=24  members=24  role=layout
 */
struct Unknown_a1_c_10 {
    u8 _pad_0x0[0xc];
    u32 f_0xc;
    u32 f_0x10;
};

/* Unknown_a1_0_4_8_c  fields=4  evidence=23  members=23  role=vec4f
 *   real members: 38d0(FUN_001238d0), a130(FUN_001ca130), cb00(FUN_001ccb00), bea0(FUN_001dbea0), f840(FUN_001df840), fdb0(FUN_001dfdb0)
 */
struct Unknown_a1_0_4_8_c {
    f32 f_0x0;   /* also deref'd */
    f32 f_0x4;
    f32 f_0x8;
    f32 f_0xc;
};

/* Unknown_a0_4_c_10  fields=3  evidence=21  members=21  role=object-like
 */
struct Unknown_a0_4_c_10 {
    u8 _pad_0x0[0x4];
    void * f_0x4;
    u8 _pad_0x8[0x4];
    void * f_0xc;
    void * f_0x10;
};

/* Unknown_a0_4_b4  fields=2  evidence=20  members=20  role=object-like
 */
struct Unknown_a0_4_b4 {
    u8 _pad_0x0[0x4];
    void * f_0x4;
    u8 _pad_0x8[0xac];
    u32 f_0xb4;
};

/* Unknown_a0_0_80  fields=2  evidence=19  members=19  role=object-like
 */
struct Unknown_a0_0_80 {
    void * f_0x0;
    u8 _pad_0x4[0x7c];
    u32 f_0x80;
};

/* Unknown_a0_4_c  fields=2  evidence=18  members=18  role=object-like
 */
struct Unknown_a0_4_c {
    u8 _pad_0x0[0x4];
    void * f_0x4;
    u8 _pad_0x8[0x4];
    void * f_0xc;
};

/* Unknown_a0_c_10  fields=2  evidence=18  members=18  role=float-pack
 */
struct Unknown_a0_c_10 {
    u8 _pad_0x0[0xc];
    f32 f_0xc;   /* also deref'd */
    f32 f_0x10;   /* also deref'd */
};

/* Unknown_a2_0_4_8  fields=3  evidence=17  members=17  role=vec3f
 *   real members: 1de0(FUN_00161de0), b3f0(FUN_0028b3f0), d7c0(FUN_0058d7c0)
 */
struct Unknown_a2_0_4_8 {
    f32 f_0x0;   /* also deref'd */
    f32 f_0x4;   /* also deref'd */
    f32 f_0x8;
};

/* Unknown_a0_0_2c  fields=2  evidence=16  members=16  role=object-like
 */
struct Unknown_a0_0_2c {
    void * f_0x0;
    u8 _pad_0x4[0x28];
    void * f_0x2c;
};

/* Unknown_a0_0_5c  fields=2  evidence=15  members=15  role=object-like
 */
struct Unknown_a0_0_5c {
    void * f_0x0;
    u8 _pad_0x4[0x58];
    u32 f_0x5c;
};

/* Unknown_a0_0_8_10  fields=3  evidence=15  members=15  role=object-like
 *   real members: c0a0(FUN_005ec0a0), d330(FUN_005ed330)
 */
struct Unknown_a0_0_8_10 {
    void * f_0x0;
    u8 _pad_0x4[0x4];
    void * f_0x8;
    u8 _pad_0xc[0x4];
    void * f_0x10;
};

/* Unknown_a0_4_10  fields=2  evidence=14  members=14  role=object-like
 */
struct Unknown_a0_4_10 {
    u8 _pad_0x0[0x4];
    void * f_0x4;
    u8 _pad_0x8[0x8];
    void * f_0x10;
};

/* Unknown_a0_0_50  fields=2  evidence=13  members=13  role=object-like
 */
struct Unknown_a0_0_50 {
    void * f_0x0;
    u8 _pad_0x4[0x4c];
    u32 f_0x50;
};

/* Unknown_a0_0_58  fields=2  evidence=13  members=13  role=object-like
 */
struct Unknown_a0_0_58 {
    void * f_0x0;
    u8 _pad_0x4[0x54];
    u32 f_0x58;
};

/* Unknown_a0_4_30  fields=2  evidence=13  members=13  role=object-like
 */
struct Unknown_a0_4_30 {
    u8 _pad_0x0[0x4];
    void * f_0x4;
    u8 _pad_0x8[0x28];
    void * f_0x30;
};

/* Unknown_a0_8_1c  fields=2  evidence=13  members=13  role=object-like
 */
struct Unknown_a0_8_1c {
    u8 _pad_0x0[0x8];
    void * f_0x8;
    u8 _pad_0xc[0x10];
    void * f_0x1c;
};

/* Unknown_a0_0_4_8_10  fields=4  evidence=12  members=12  role=layout
 *   real members: b3f0(FUN_0028b3f0)
 */
struct Unknown_a0_0_4_8_10 {
    f32 f_0x0;   /* also deref'd */
    f32 f_0x4;
    f32 f_0x8;   /* also deref'd */
    u8 _pad_0xc[0x4];
    void * f_0x10;
};

/* Unknown_a0_0_4_8_c_10  fields=5  evidence=12  members=12  role=layout
 *   real members: e060(FUN_0026e060), e1a0(FUN_0026e1a0), e2e0(FUN_0026e2e0), e420(FUN_0026e420)
 */
struct Unknown_a0_0_4_8_c_10 {
    f32 f_0x0;   /* also deref'd */
    void * f_0x4;
    f32 f_0x8;
    f32 f_0xc;   /* also deref'd */
    f32 f_0x10;   /* also deref'd */
};

/* Unknown_a0_0_c  fields=2  evidence=12  members=12  role=object-like
 */
struct Unknown_a0_0_c {
    void * f_0x0;
    u8 _pad_0x4[0x8];
    void * f_0xc;
};

/* Unknown_a0_0_14_18_1c  fields=4  evidence=11  members=11  role=float-pack
 */
struct Unknown_a0_0_14_18_1c {
    f32 f_0x0;   /* also deref'd */
    u8 _pad_0x4[0x10];
    f32 f_0x14;
    f32 f_0x18;   /* also deref'd */
    f32 f_0x1c;   /* also deref'd */
};

/* Unknown_a0_8_34  fields=2  evidence=11  members=11  role=object-like
 */
struct Unknown_a0_8_34 {
    u8 _pad_0x0[0x8];
    void * f_0x8;
    u8 _pad_0xc[0x28];
    void * f_0x34;
};

/* Unknown_a0_8_14  fields=2  evidence=10  members=10  role=float-pack
 */
struct Unknown_a0_8_14 {
    u8 _pad_0x0[0x8];
    f32 f_0x8;
    u8 _pad_0xc[0x8];
    f32 f_0x14;   /* also deref'd */
};

/* --- opaque forward decls used by signatures.h (not promoted) --- */
struct Unknown_a0_0;
struct Unknown_a0_0_1;
struct Unknown_a0_0_10_20;
struct Unknown_a0_0_10_2c_38_3c_44_60_80_94_1b0;
struct Unknown_a0_0_4_8_10_28_2c_64;
struct Unknown_a0_0_4_8_c_10_14;
struct Unknown_a0_0_4_8_c_10_14_18_1c_20_24_28_2c_30_34_38_3c;
struct Unknown_a0_0_4_c_10;
struct Unknown_a0_0_8_9;
struct Unknown_a0_14_64;
struct Unknown_a0_1944;
struct Unknown_a0_1f0;
struct Unknown_a0_38;
struct Unknown_a0_4_8_a4;
struct Unknown_a0_4_8_ac;
struct Unknown_a0_4_8_c;
struct Unknown_a0_4ec;
struct Unknown_a0_8;
struct Unknown_a0_e;
struct Unknown_a1_0;
struct Unknown_a1_0_10_14_18;
struct Unknown_a1_0_4_8_c_10_14_18_1c_20;
struct Unknown_a1_0_4_8_c_10_14_18_1c_20_24_28_2c_30_34_38_3c;
struct Unknown_a1_0_4_8_f;
struct Unknown_a1_0_8_10;
struct Unknown_a1_18;
struct Unknown_a1_28;
struct Unknown_a1_8;
struct Unknown_a1_8_18_28;
struct Unknown_a1_c;
struct Unknown_a2_0;
struct Unknown_a2_0_10;
struct Unknown_a2_0_4;
struct Unknown_a2_18;
struct Unknown_a2_c;
struct Unknown_a3_0;
struct Unknown_a3_20;

#endif /* _CNK_ENGINE_TYPES_H */
