#!/usr/bin/env python
"""Phase 4C - recover function signatures for all logic functions.

emit_structs.py (Phase 3E) only prototypes the ~95 real functions whose
arguments already carried a struct label. This step covers the *whole*
actionable set: all 214 real_c + real_logic functions get an evidence-based
prototype.

Type resolution per argument slot:
  1. propagated label that names a promoted struct in include/engine/types.h
     -> use it (highest provenance wins, DIRECT first).
  2. otherwise raw inferred kind: aX=ptr -> void *, aX=int -> int.
Return kind from the binary: ptr -> void *, int -> int, else void.
A `known-good` column marks real_c (symboled) rows so the reviewer can
trust the recovered signatures against Ghidra - real_c are already named.

Outputs:
    include/engine/logic_signatures.h   all 214 typed prototypes
    src/decomp/analysis/signature_recovery.csv  address, proto, ctype args,
                                                return ctype, sources, status
"""
import collections
import csv
import io
import os

OUT_DIR = os.path.join("src", "decomp", "analysis")
INC_DIR = os.path.join("include", "engine")

prov_rank = {"DIRECT": 5, "STRUCT_FIELD": 4, "CALL_PROPAGATED": 3,
             "RETURN_PROPAGATED": 2, "HEURISTIC": 1}


def load_csv(path):
    with io.open(path, encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def main():
    types = {r["address"]: r for r in load_csv(os.path.join(OUT_DIR, "inferred_types.csv"))}
    prop = load_csv(os.path.join(OUT_DIR, "propagated_types.csv"))
    states = {r["address"]: r for r in load_csv(os.path.join(OUT_DIR, "symbols.csv"))}
    # promoted struct names = ones defined in types.h
    prom = set()
    with io.open(os.path.join(INC_DIR, "types.h"), encoding="utf-8") as f:
        for ln in f:
            if ln.startswith("struct "):
                nm = ln.strip().split()[1].rstrip("{")
                prom.add(nm)

    # best propagated label per (addr, arg)
    best = collections.defaultdict(dict)
    for r in prop:
        a, arg = r["address"], r["arg"]
        cur = best[a].get(arg)
        if cur is None or prov_rank.get(r["provenance"], 0) > \
                prov_rank.get(cur[1], 0):
            best[a][arg] = (r["label"], r["provenance"])

    def arg_c(a, arg, targ):
        lab = best.get(a, {}).get(arg)
        if lab and lab[0] in prom:
            return "struct %s *" % lab[0], ("struct %s" % lab[0])
        if "ptr" in (targ or ""):
            return "void *", "ptr"
        if "int" in (targ or ""):
            return "int", "int"
        return None, None

    def ret_c(a):
        rk = types[a].get("return_kind", "")
        if rk == "ptr":
            return "void *"
        if rk == "int":
            return "int"
        return "void"

    rows = []
    for addr, t in types.items():
        if t["status"] not in ("real_c", "real_logic"):
            continue
        st = states.get(addr, {})
        args_tmp = []
        args_src = []
        for k in range(4):
            slot = "a%d" % k
            tag = None
            for tok in (t.get("args", "") or "").split(";"):
                if tok.startswith(slot + "="):
                    tag = tok.split("=", 1)[1]
                    break
            c, src = arg_c(addr, slot, tag)
            if c is None:
                continue
            args_tmp.append("%s a%d" % (c, k))
            args_src.append("%s:%s" % (slot, src))
        rows.append({
            "address": addr,
            "name": st.get("name") or t.get("name", addr),
            "status": t["status"],
            "known_good": "1" if (t["status"] == "real_c" and st.get("name")) else "0",
            "return_c": ret_c(addr),
            "args_c": ", ".join(a for a in args_tmp) if args_tmp else "",
            "args_src": "|".join(args_src),
        })

    rows.sort(key=lambda r: (r["status"] != "real_logic", r["address"]))

    lines = ["/* ============================================================================",
             " * include/engine/logic_signatures.h - recovered prototypes (Phase 4C)",
             " * machine-generated by tools/emit_signatures.py; all %d logic functions." % len(rows),
             " * Type resolution: propagated struct label (promoted in types.h) else raw",
             " * inferred ptr/int. known_good legend: 1 = symboled real_c (Ghidra-verified).",
             " * ======================================================================== */",
             "",
             "#ifndef _CNK_ENGINE_LOGIC_SIGNATURES_H",
             "#define _CNK_ENGINE_LOGIC_SIGNATURES_H",
             "",
             "#include \"types.h\"",
             "",
             "/* %d prototypes */" % len(rows)]
    for r in rows:
        g = "K" if r["known_good"] == "1" else " "
        args = r["args_c"] if r["args_c"] else "void"
        lines.append("/* %s %s [%s] %s */" %
                     (r["address"], r["name"], g, r["args_src"]))
        lines.append("%s %s(%s);" % (r["return_c"], r["name"], args))
    lines.append("")
    lines.append("#endif")
    lines.append("")
    with io.open(os.path.join(INC_DIR, "logic_signatures.h"), "w",
                 encoding="utf-8") as f:
        f.write("\n".join(lines))

    with io.open(os.path.join(OUT_DIR, "signature_recovery.csv"), "w",
                 encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)

    n_typed = sum(1 for r in rows if r["args_c"])
    print("wrote include/engine/logic_signatures.h (%d prototypes, %d with args)" %
          (len(rows), n_typed))
    print("wrote src/decomp/analysis/signature_recovery.csv")


if __name__ == "__main__":
    main()