#!/usr/bin/env python
"""Phase 3E - promote evidence to compilable headers.

Reads the Phase 3B/3C analysis products and emits real C headers so that
hand-written decompilations in src/decomp/real can use named struct types.

Promotion rules (from docs/10_TYPES.md "Next steps" #3) are conservative:
a candidate becomes a header struct when it has >= MIN_EVIDENCE total
field accesses AND >= MIN_MEMBERS functions sharing the exact signature.
Shared fields are only surfaced as comments (seeds) until a human orders a
real substruct. Everything keeps its deterministic (layout-derived) name;
no invented identifiers.

Outputs:
    include/engine/types.h         promoted anonymous struct definitions
    include/engine/substruct_seeds.h  shared-field seeds (evidence >= 3)
    include/engine/signatures.h    typed prototypes for real_c/real_logic
                                   functions whose args were struct-typed
"""
import collections
import csv
import io
import json
import os
import sys

OUT_DIR = os.path.join("src", "decomp", "analysis")
INC_DIR = os.path.join("include", "engine")
MIN_EVIDENCE = 10
MIN_MEMBERS = 3
TYPE_TBF = {  # (json type, width) -> C type name
    ("char", 1): "u8", ("short", 2): "u16",
    ("int", 1): "u8", ("int", 2): "u16", ("int", 4): "u32",
    ("int", 8): "u32", ("i64", 8): "u64",
    ("float", 4): "f32",
    ("vec", 16): "f32[4]", ("vec", 4): "f32",
    ("ptr", 4): "void *",
}
FIELD_TYPES = [("ptr", 4), ("i64", 8), ("float", 4), ("vec", 16),
               ("int", 8), ("int", 4), ("short", 2), ("char", 1),
               ("int", 2), ("int", 1)]


def load_csv(path):
    with io.open(path, encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def field_c_type(f):
    t = f.get("type")
    w = int(f.get("width", 4))
    if t == "ptr":
        return "void *", ""
    base = TYPE_TBF.get((t, w), "u32")
    if base.endswith("[4]"):
        return base[:-3], "[4]"
    return base, ""


def field_id(off):
    return "f_0x%x" % off


def role_of(fields):
    """Heuristic role tag from layout (comment only, traceable)."""
    pure_float = all(f.get("type") in ("float", "vec") for f in fields)
    offs = sorted(f["offset"] for f in fields)
    if pure_float:
        if offs == [0, 4]:
            return "vec2f"
        if offs == [0, 4, 8]:
            return "vec3f"
        if offs == [0, 4, 8, 0xc]:
            return "vec4f"
        if offs == [0, 4, 8, 0xc, 0x10, 0x14, 0x18, 0x1c]:
            return "mat4f"
        return "float-pack"
    if fields and fields[0].get("type") == "ptr":
        return "object-like"
    return "layout"


def main():
    os.makedirs(INC_DIR, exist_ok=True)
    with io.open(os.path.join(OUT_DIR, "inferred_structs.json"),
                 encoding="utf-8") as f:
        j = json.load(f)
    structs = j["structs"]
    shared = j["shared_fields"]
    sym = {r["address"]: r for r in load_csv(os.path.join(OUT_DIR, "symbols.csv"))}
    prop = load_csv(os.path.join(OUT_DIR, "propagated_types.csv"))
    types = {r["address"]: r for r in load_csv(os.path.join(OUT_DIR, "inferred_types.csv"))}

    def sym_for(a):
        s = sym.get(a, {})
        return s.get("name", a) if s.get("status") in ("real_c", "real_logic") else None

    want = collections.defaultdict(dict)
    for r in prop:
        a = r["address"]
        if sym.get(a, {}).get("status") not in ("real_c", "real_logic"):
            continue
        if not r["label"].startswith("Unknown_"):
            continue
        want[a][r["arg"]] = r["label"]
    order = sorted(want)

    # ---------------- include/engine/types.h --------------------------------
    promoted = [s for s in structs
                if s["evidence"] >= MIN_EVIDENCE and
                len(s.get("functions", [])) >= MIN_MEMBERS and
                len(s.get("fields", [])) >= 2]
    promoted.sort(key=lambda s: (-s["evidence"], s["name"]))

    lines = []
    lines.append("/* ============================================================================")
    lines.append(" * include/engine/types.h - Phase 3E promoted anonymous structs (SLUS_206.49)")
    lines.append(" * machine-generated by tools/emit_structs.py; regenerate, do not hand-edit.")
    lines.append(" * Layout-derived names are deterministic from (arg, offsets): no invented ids.")
    lines.append(" * Promotion: evidence >= %d, members >= %d, fields >= 2 (of %d candidates)." %
                 (MIN_EVIDENCE, MIN_MEMBERS, len(structs)))
    lines.append(" * ======================================================================== */")
    lines.append("")
    lines.append("#ifndef _CNK_ENGINE_TYPES_H")
    lines.append("#define _CNK_ENGINE_TYPES_H")
    lines.append("")
    lines.append("typedef unsigned char   u8;")
    lines.append("typedef unsigned short  u16;")
    lines.append("typedef unsigned int    u32;")
    lines.append("typedef unsigned long long u64;")
    lines.append("typedef float           f32;")
    lines.append("")
    lines.append("/* --- %d struct bodies --- */" % len(promoted))
    lines.append("")
    for s in promoted:
        name = s["name"]
        nf = len(s["fields"])
        role = role_of([f for f in s["fields"] if f.get("type") != "vec"] or s["fields"])
        real_members = [a for a in s.get("functions", []) if sym_for(a)]
        lines.append("/* %s  fields=%d  evidence=%d  members=%d  role=%s" %
                     (name, nf, s["evidence"], len(s.get("functions", [])), role))
        if real_members:
            lines.append(" *   real members: %s" %
                         ", ".join("%s(%s)" % (a[6:10], sym_for(a)) for a in real_members[:6]))
        lines.append(" */")
        lines.append("struct %s {" % name)
        fields = sorted(s["fields"], key=lambda x: x["offset"])
        cursor = 0
        for f in fields:
            ctype, suffix = field_c_type(f)
            note = ""
            if f.get("ptr") and not ctype.startswith("void"):
                note = "   /* also deref'd */"
            if f["offset"] > cursor:
                lines.append("    u8 _pad_0x%x[0x%x];" %
                             (cursor, f["offset"] - cursor))
            lines.append("    %s %s%s;%s" % (ctype, field_id(f["offset"]),
                                             suffix, note))
            w = int(f.get("width", 4))
            cursor = f["offset"] + w
        lines.append("};")
        lines.append("")
    opaque = sorted({lab for labs in want.values() for lab in labs.values()} -
                    {s["name"] for s in promoted})
    lines.append("/* --- opaque forward decls used by signatures.h (not promoted) --- */")
    for o in opaque:
        lines.append("struct %s;" % o)
    lines.append("")
    lines.append("#endif /* _CNK_ENGINE_TYPES_H */")
    lines.append("")
    with io.open(os.path.join(INC_DIR, "types.h"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    # ---------------- include/engine/substruct_seeds.h ------------------------
    seeds = [x for x in shared if x["evidence"] >= 3]
    seeds.sort(key=lambda x: (-x["evidence"], x["arg"], x["offset"]))
    sl = []
    sl.append("/* ============================================================================")
    sl.append(" * include/engine/substruct_seeds.h - shared-field seeds (Phase 3B mesh)")
    sl.append(" * machine-generated; one-field overlaps across >=3 functions. These are NOT")
    sl.append(" * promoted structs - they are ordering hints for substructs the caller must")
    sl.append(" * assemble. arg is the slot aX; evidence = functions touching the field.")
    sl.append(" * ======================================================================== */")
    sl.append("")
    sl.append("#ifndef _CNK_ENGINE_SUBSTRUCT_SEEDS_H")
    sl.append("#define _CNK_ENGINE_SUBSTRUCT_SEEDS_H")
    sl.append("")
    sl.append("#include \"types.h\"")
    sl.append("")
    sl.append("/* %d seeds with evidence>=3 */" % len(seeds))
    sl.append("")
    for x in seeds:
        sl.append("/* a%d+0x%x : %s (w%d) x%d   e.g. %s */" %
                  (x["arg"], x["offset"], x["type"], x["width"], x["evidence"],
                   ", ".join(a[6:10] for a in x["functions"][:6])))
    sl.append("")
    sl.append("#endif")
    sl.append("")
    with io.open(os.path.join(INC_DIR, "substruct_seeds.h"), "w",
                 encoding="utf-8") as f:
        f.write("\n".join(sl))

    # ---------------- include/engine/signatures.h -----------------------------
    def ret_c(a):
        rk = types[a]["return_kind"]
        if rk == "ptr":
            return "void *"
        if rk == "int":
            return "int"
        return "void"

    hl = []
    hl.append("/* ============================================================================")
    hl.append(" * include/engine/signatures.h - typed prototypes for real functions (Phase 3E)")
    hl.append(" * machine-generated; only args with a promoted struct label are replaced, the")
    hl.append(" * rest keep the raw inferred kind (ptr -> void *, int -> int, - -> skipped).")
    hl.append(" * ======================================================================== */")
    hl.append("")
    hl.append("#include \"types.h\"")
    hl.append("")
    hl.append("/* %d prototypes */" % len(order))
    for a in order:
        s = sym.get(a, {})
        lab = want[a]
        args = []
        for k in range(4):
            slot = "a%d" % k
            l = lab.get(slot)
            t = types[a].get("args", "")
            if l:
                args.append("%s *%s" % (l, slot))
            elif ("%s=ptr" % slot) in t:
                args.append("void *%s" % slot)
            elif ("%s=int" % slot) in t:
                args.append("int %s" % slot)
        hl.append("/* %s  %s  module=%s  (return %s) */" %
                  (a, s.get("name", a), s.get("module", "-"),
                   types[a]["return_kind"]))
        hl.append("%s %s(%s);" %
                  (ret_c(a), s.get("name", a),
                   ", ".join(args) if args else "void"))
    with io.open(os.path.join(INC_DIR, "signatures.h"), "w", encoding="utf-8") as f:
        f.write("\n".join(hl))

    print("wrote %s/types.h            (%d promoted structs of %d)" %
          (INC_DIR, len(promoted), len(structs)))
    print("wrote %s/substruct_seeds.h  (%d seeds)" % (INC_DIR, len(seeds)))
    print("wrote %s/signatures.h       (%d typed prototypes)" % (INC_DIR, len(order)))


if __name__ == "__main__":
    main()