#!/usr/bin/env python
"""Phase 4B - candidate structs for human review (Roadmap step 2).

Turns the Phase 3H composed co-occurrence groups into *draft* C struct
definitions the reviewer can open side-by-side with a recovery sheet.
Layout-derived names only (`Unknown_a0_0x...`), full evidence comments.

Promotion is deliberately NOT automatic: groups listed here are candidates.
A group gets a real name only after a human confirms it against Ghidra and
replaces the name at the top of the comment block.

Output:
    include/engine/recovered_structs.h   draft definitions (do not use in
                                         signatures.h until promoted)
    src/decomp/analysis/recovered_structs.md  readable summary
"""
import collections
import csv
import io
import json
import os

OUT_DIR = os.path.join("src", "decomp", "analysis")
INC_DIR = os.path.join("include", "engine")
MIN_STRENGTH = 3
MAX_PREVIEW = 48          # members per struct preview


def load_csv(path):
    with io.open(path, encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def c_type(t, w):
    m = {"float": "f32", "ptr": "void *"}
    if t in m:
        return m[t]
    return {1: "u8", 2: "u16", 4: "u32", 8: "u64"}.get(w, "u32")


def name_of(arg, offsets):
    return "Unknown_a%d_%s" % (arg, "_".join("0x%x" % o for o in offsets))


def main():
    with io.open(os.path.join(OUT_DIR, "composed_structs.json"),
                 encoding="utf-8") as f:
        comp = json.load(f)
    groups = [g for g in comp["cooccur_groups"] if g["strength"] >= MIN_STRENGTH]
    groups.sort(key=lambda g: (-len(g["members"]), -g["strength"],
                               g["arg"], g["offsets"][0]))

    # how many times each offset is shared (per arg) for the md
    shared = comp["member_derives"]

    lines = ["/* ============================================================================",
             " * include/engine/recovered_structs.h - Type-B composed candidates (Phase 4B)",
             " * machine-generated by tools/recover_structs.py - DRAFT review surface.",
             " * Trailing fields compete with an unshared, larger context: the group only",
             " * proves that these offsets co-occur inside one object layout, not that the",
             " * struct starts at the first offset. Names are layout-derived; do not use",
             " * in signatures.h until a human promotes them.",
             " * ======================================================================== */",
             "",
             "#ifndef _CNK_ENGINE_RECOVERED_STRUCTS_H",
             "#define _CNK_ENGINE_RECOVERED_STRUCTS_H",
             "",
             "/* %d candidates (strength >= %d co-occurring functions) */" %
             (len(groups), MIN_STRENGTH),
             ""]

    for g in groups:
        name = name_of(g["arg"], g["offsets"])
        lines.append("/* ------------------------------------------------------------")
        lines.append(" * %s  arg a%d  strength %d" % (name, g["arg"], g["strength"]))
        lines.append(" * comment: PROMOTE ME -> rename and rewrite members")
        lines.append(" * offsets: %s" % ", ".join("0x%x" % o for o in g["offsets"]))
        lines.append(" * ------------------------------------------------------------ */")
        lines.append("// struct %s {" % name)
        for m in g["members"][:MAX_PREVIEW]:
            mark = "  /* split-site */ " if m["split"] else ""
            lines.append("//     %s f_0x%x;%s /* ev %d */" %
                         (c_type(m["type"], m["width"]), m["offset"],
                          mark, m["evidence"]))
        if len(g["members"]) > MAX_PREVIEW:
            lines.append("//     /* ... %d more members ... */" %
                         (len(g["members"]) - MAX_PREVIEW))
        lines.append("// };")
        lines.append("")
    lines.append("#endif")
    lines.append("")
    with io.open(os.path.join(INC_DIR, "recovered_structs.h"), "w",
                 encoding="utf-8") as f:
        f.write("\n".join(lines))

    md = ["# Phase 4B - composed candidate structs (draft)",
          "",
          "Groups from Phase 3H with strength >= %d, strongest first." % MIN_STRENGTH,
          "Open each next to its recovery sheet; promote by renaming,",
          "then uncomment in recovered_structs.h.",
          "",
          "## Top-20 candidates",
          ""]
    for g in groups[:20]:
        md.append("- `%s`  a%d  [%s]  strength %d  members %d  split %d" %
                  (name_of(g["arg"], g["offsets"]), g["arg"],
                   ", ".join("0x%x" % o for o in g["offsets"]),
                   g["strength"], len(g["members"]),
                   sum(1 for m in g["members"] if m["split"])))
    md.append("")
    with io.open(os.path.join(OUT_DIR, "recovered_structs.md"), "w",
                 encoding="utf-8") as f:
        f.write("\n".join(md))

    print("wrote include/engine/recovered_structs.h (%d draft candidates)" %
          len(groups))
    print("wrote src/decomp/analysis/recovered_structs.md")


if __name__ == "__main__":
    main()